[project]
name = "todo"
version = "0.0.1"
description = "A to-do list using FastAPI"
authors = [
    {name = "M", email = "m@mathsistor.com"},
]
dependencies = [
    "fastapi[all]>=0.104.1",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.scripts]
run-server = "uvicorn todo.main:app"
lint = "ruff check --force-exclude"
format = "ruff format --force-exclude"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.3",
]
lint = [
    "ruff>=0.1.7",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff]
select = [
    # "D", # pydocstyle
    "E", # pycodestyle errors
    "F", # pyflakes
    "I",  # isort
    "N", # pep8-naming
    "W", # pycodestyle warnings
]
